version: '3.8'

services:
  # 1. JAVA UYGULAMASI
  app:
    container_name: ticket-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - redis
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/flashticket_db
      SPRING_DATA_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      JWT_SECRET_KEY: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

  # 2. VERÄ°TABANI
  postgres-db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flashticket_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # 3. REDIS
  redis:
    image: redis:alpine
    container_name: flashticket-redis
    ports:
      - "6379:6379"

  # 4. RABBITMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: flashticket-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres-data: