version: '3.8'

services:
  # 1. VERÄ°TABANI
  postgres-db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flashticket_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # 2. REDIS
  redis:
    image: redis:alpine
    container_name: flashticket-redis
    ports:
      - "6379:6379"
    restart: always

  # 3. RABBITMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: flashticket-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

volumes:
  postgres-data: